### ISSUE TITLE
Unable to dlopen extracted images.

### ISSUE THREAD

**Issue by PoomSmart** [arandomdev/DyldExtractor#31] opened 2021-12-18 03:52 UTC
**Describe the bug**

DyldExtractor 1.0.8

Binary path: `/System/Library/VideoDecoders/AVD.videodecoder`

When `dlopen()`-ing it, this happens:

```
[Common.x:81] AVD handle 0 (dlopen(/System/Library/VideoDecoders/AVD.videodecoder, 2): no suitable image found.  Did find:
	/System/Library/VideoDecoders/AVD.videodecoder: malformed mach-o image: dyld weak bind info overlaps bind info
	/System/Library/VideoDecoders/AVD.videodecoder: malformed mach-o image: dyld weak bind info overlaps bind info)
```

**To Reproduce**
1. iOS version 14.6
2. DYLD target device and identifier https://ipsw.me/download/iPhone10,6/18F72

**Additional context**

**Comment by arandomdev** [comment] 2021-12-19 03:25
So, the main scope of the project is to help with reverse engineering. Generating a runnable image is a very hard goal.

For the error above, I found that the loader validates the dyld info in a specific order, which can be found [here](https://opensource.apple.com/source/dyld/dyld-519.2.2/src/ImageLoaderMachO.cpp.auto.html#:~:text=dyld%20weak%20bind%20info%20size%20overflow). I changed the order of the dyld info command with d5023c3 and was able to get pass the error.

Though the problems do not end here, DyldExtractor does not generate rebase info, which breaks PIE. And for newer caches and especially arm64e, critical information might be stripped from the cache (though I haven't confirmed this).

And a while ago, when I tried creating runnable images, I ran into a weird issue where the loader would incorrectly read the LINKEDIT segment at a 0x1000 offset. I think this is because each segment is so far apart from each other, which I can't reverse correctly because the cache does not contain the info to do so.

And despite my best efforts, there is a high chance that there are mistakes and errors when extracting images. Which would make it unreliable for tweaks.

I'll keep this issue open as I really want this to work, but it's unlikely that anything would be out soon.

**Comment by PoomSmart** [comment] 2021-12-19 03:51
@arandomdev That commit gets passed the error. Great work. Now the problem is signing. I `dlopen`-ed this on iPhone SE 1st gen and got `can't map segments into 16KB pages`.

Signed the binary with `codesign -f -s - AVD.videodecoder`.

A great step forward still!

**Comment by PoomSmart** [comment] 2021-12-19 05:15
Output from `otool`:

```
thatchaponunp@Thatchapons-MacBook-Pro ~ % otool -l /Users/thatchaponunp/Documents/Tweaks/ytuhd/layout/System/Library/VideoDecoders/AVD.videodecoder
/Users/thatchaponunp/Documents/Tweaks/ytuhd/layout/System/Library/VideoDecoders/AVD.videodecoder:
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 792
  segname __TEXT
   vmaddr 0x00000001cab90000
   vmsize 0x000000000002d000
  fileoff 0
 filesize 184320
  maxprot 0x00000005
 initprot 0x00000005
   nsects 9
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x00000001cab91354
      size 0x000000000002404c
    offset 4948
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x00000001cabb53a0
      size 0x0000000000000924
    offset 152480
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 12 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x00000001cabb5cc4
      size 0x000000000000090c
    offset 154820
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x00000001cabb65d0
      size 0x0000000000000542
    offset 157136
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x00000001cabb6b12
      size 0x0000000000005f85
    offset 158482
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __gcc_except_tab
   segname __TEXT
      addr 0x00000001cabbca98
      size 0x00000000000000cc
    offset 182936
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __oslogstring
   segname __TEXT
      addr 0x00000001cabbcb64
      size 0x0000000000000003
    offset 183140
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x00000001cabbcb68
      size 0x00000000000003e4
    offset 183144
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __eh_frame
   segname __TEXT
      addr 0x00000001cabbcf50
      size 0x00000000000000b0
    offset 184144
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 392
  segname __DATA_CONST
   vmaddr 0x00000001e16e9f00
   vmsize 0x0000000000000f28
  fileoff 196608
 filesize 3880
  maxprot 0x00000003
 initprot 0x00000003
   nsects 4
    flags 0x0
Section
  sectname __got
   segname __DATA_CONST
      addr 0x00000001e16e9f00
      size 0x0000000000000290
    offset 196608
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 195 (index into indirect symbol table)
 reserved2 0
Section
  sectname __la_symbol_ptr
   segname __DATA_CONST
      addr 0x00000001e16ea190
      size 0x00000000000005f8
    offset 197264
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 277 (index into indirect symbol table)
 reserved2 0
Section
  sectname __const
   segname __DATA_CONST
      addr 0x00000001e16ea788
      size 0x00000000000002a0
    offset 198792
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cfstring
   segname __DATA_CONST
      addr 0x00000001e16eaa28
      size 0x0000000000000400
    offset 199464
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 392
  segname __DATA
   vmaddr 0x00000001da05d0f8
   vmsize 0x00000000000000a8
  fileoff 212992
 filesize 168
  maxprot 0x00000003
 initprot 0x00000003
   nsects 4
    flags 0x0
Section
  sectname __la_weak_ptr
   segname __DATA
      addr 0x00000001da05d0f8
      size 0x0000000000000020
    offset 212992
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 468 (index into indirect symbol table)
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x00000001da05d118
      size 0x0000000000000028
    offset 213024
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x00000001da05d140
      size 0x0000000000000031
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Section
  sectname __common
   segname __DATA
      addr 0x00000001da05d178
      size 0x0000000000000028
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 3
      cmd LC_SEGMENT_64
  cmdsize 232
  segname __DATA_DIRTY
   vmaddr 0x00000001d2e945b0
   vmsize 0x0000000000000038
  fileoff 229376
 filesize 56
  maxprot 0x00000003
 initprot 0x00000003
   nsects 2
    flags 0x0
Section
  sectname __data
   segname __DATA_DIRTY
      addr 0x00000001d2e945b0
      size 0x0000000000000030
    offset 229376
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA_DIRTY
      addr 0x00000001d2e945e0
      size 0x0000000000000008
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 4
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x00000001e5cec000
   vmsize 0x0000000000010000
  fileoff 245760
 filesize 61872
  maxprot 0x00000001
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 5
          cmd LC_ID_DYLIB
      cmdsize 72
         name /System/Library/VideoDecoders/AVD.videodecoder (offset 24)
   time stamp 2 Thu Jan  1 07:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 6
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 0
    rebase_size 0
       bind_off 245760
      bind_size 3488
  weak_bind_off 249248
 weak_bind_size 88
  lazy_bind_off 249336
 lazy_bind_size 5792
     export_off 255128
    export_size 24
Load command 7
     cmd LC_SYMTAB
 cmdsize 24
  symoff 255152
   nsyms 610
  stroff 267248
 strsize 19847
Load command 8
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 330
     iextdefsym 330
     nextdefsym 1
      iundefsym 331
      nundefsym 279
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 265360
  nindirectsyms 472
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 9
     cmd LC_UUID
 cmdsize 24
    uuid CDF594AA-B2BC-3B9E-AF88-9C2FBCF291D8
Load command 10
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 2
    minos 14.6
      sdk 14.6
   ntools 1
     tool 3
  version 650.6
Load command 11
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 382.0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/Foundation.framework/Foundation (offset 24)
   time stamp 2 Thu Jan  1 07:00:02 1970
      current version 1776.103.0
compatibility version 300.0.0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/CoreVideo.framework/CoreVideo (offset 24)
   time stamp 2 Thu Jan  1 07:00:02 1970
      current version 1.5.0
compatibility version 1.2.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/VideoToolbox.framework/VideoToolbox (offset 24)
   time stamp 2 Thu Jan  1 07:00:02 1970
      current version 1.0.0
compatibility version 1.0.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/CoreMedia.framework/CoreMedia (offset 24)
   time stamp 2 Thu Jan  1 07:00:02 1970
      current version 1.0.0
compatibility version 1.0.0
Load command 16
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (offset 24)
   time stamp 2 Thu Jan  1 07:00:02 1970
      current version 1776.103.0
compatibility version 150.0.0
Load command 17
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (offset 24)
   time stamp 2 Thu Jan  1 07:00:02 1970
      current version 275.0.0
compatibility version 1.0.0
Load command 18
          cmd LC_LOAD_DYLIB
      cmdsize 88
         name /System/Library/Frameworks/IOSurface.framework/IOSurface (offset 24)
   time stamp 2 Thu Jan  1 07:00:02 1970
      current version 1.0.0
compatibility version 1.0.0
Load command 19
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libMobileGestalt.dylib (offset 24)
   time stamp 2 Thu Jan  1 07:00:02 1970
      current version 1.0.0
compatibility version 1.0.0
Load command 20
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libc++.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 07:00:02 1970
      current version 905.6.0
compatibility version 1.0.0
Load command 21
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 07:00:02 1970
      current version 1292.120.1
compatibility version 1.0.0
Load command 22
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 264912
 datasize 448
Load command 23
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 265360
 datasize 0
Load command 24
      cmd LC_CODE_SIGNATURE
  cmdsize 16
  dataoff 287104
 datasize 20528
```

**Comment by arandomdev** [comment] 2022-01-07 03:01
So great news! I was able to extract AVD.videodecoder and successfully call `AVDRegister`. The changes are available on the [beta branch](https://github.com/arandomdev/DyldExtractor/tree/beta).

I tried to look at your code so I could test more than one function, but I didn't make it very far.
though, in order to make it work, I had to set the environment variable `DYLD_BIND_AT_LAUNCH=1`, `RTLD_LAZY` and `RTLD_NOW` doesn't seem to effect it.

**Comment by PoomSmart** [comment] 2022-01-07 14:58
@arandomdev On what device did you test it on?

**Comment by arandomdev** [comment] 2022-01-07 15:15
iPhone X, 14.3, 10,3

**Comment by PoomSmart** [comment] 2022-01-07 15:32
@arandomdev My target are devices older than iPhone X, such as iPhone SE 1st gen which only complains about `can't map segments into 16KB pages`.

**Comment by arandomdev** [comment] 2022-01-07 15:35
Are you running in the beta branch? Also, try to change the page size constant in extraction_context.py to 0x1000

**Comment by PoomSmart** [comment] 2022-01-07 15:40
@arandomdev I'm already on the `beta` branch and changing page size constant to `0x1000` results in the same error above.

**Comment by PoomSmart** [comment] 2022-01-07 15:45
@arandomdev Alright, I got a new error now:

```
[Settings.x:35] AVD dlopen(/System/Library/VideoDecoders/AVD.videodecoder, 2): no suitable image found.  Did find:
	/System/Library/VideoDecoders/AVD.videodecoder: mmap() errno=22 at address=0x2A8304000, size=0x000005E8 segment=__DATA_DIRTY in Segment::map() mapping /System/Library/VideoDecoders/AVD.videodecoder
	/System/Library/VideoDecoders/AVD.videodecoder: stat() failed with errno=34
```

**Comment by arandomdev** [comment] 2022-01-07 15:59
What device and iOS are you using, I might be able to try it on my 5s.

**Comment by arandomdev** [comment] 2022-01-07 18:16
Unfortunately, I am having a hard time getting my 5s jailbroken. But this is what I am using for my test script.

``` c
#include <dlfcn.h>
#include <stdio.h>

typedef void (AVDRegister_t)(void);

int main(int argc, char *argv[], char *envp[]) {
	void *handle = dlopen("/Applications/TestEnv/AVD.videodecoder", RTLD_LAZY);
	printf("\n\x1b[36mHello!\x1b[0m\n");

	AVDRegister_t *AVDRegister = (AVDRegister_t *)dlsym(handle, "AVDRegister");
	AVDRegister();

	printf("\n\x1b[36mGood Bye!\x1b[0m\n");
	return 0;
}

```

**Comment by arandomdev** [comment] 2022-01-07 22:58
I finally got my 5s jailbroken, but it complained about a missing symbol. So, I think that iOS 12.5.5 is too old for the 14.6 AVD.videodecoder. Luckly, I just got access to Corellium, and will try it on there.

**Comment by arandomdev** [comment] 2022-01-08 00:32
I tried the test program on the simulated device, and dlopen-ing seemed to work for me.
Are you using the same cache as stated above? I also pushed 63a93d9 that should fix an issue with ldid.

If you would like, we can swap binaries as well.

**Comment by PoomSmart** [comment] 2022-01-08 01:46
@arandomdev I got the same error even with that latest commit.

Here's my binary (signed with `ldid`):

[AVD.videodecoder.zip](https://github.com/arandomdev/DyldExtractor/files/7832172/AVD.videodecoder.zip)

**Comment by arandomdev** [comment] 2022-01-09 22:53
So now that images are technically dlopen-able, I'm going to close this issue.
Though there are still a lot of work that needs to be done.

**Closed by arandomdev** 2022-01-09 22:53 UTC
